export const API = {
  ADMIN_STATUS: '/v1/admin/status',
  ADMIN_KILL_SWITCH: '/v1/admin/kill-switch',
  ADMIN_KILL_SWITCH_ESCALATE: '/v1/admin/kill-switch/escalate',
  ADMIN_RECOVER: '/v1/admin/recover',
  ADMIN_SHUTDOWN: '/v1/admin/shutdown',
  ADMIN_ROTATE_SECRET: '/v1/admin/rotate-secret',
  WALLETS: '/v1/wallets',
  WALLET: (id: string) => `/v1/wallets/${id}`,
  SESSIONS: '/v1/sessions',
  SESSION: (id: string) => `/v1/sessions/${id}`,
  POLICIES: '/v1/policies',
  POLICY: (id: string) => `/v1/policies/${id}`,
  ADMIN_NOTIFICATIONS_STATUS: '/v1/admin/notifications/status',
  ADMIN_NOTIFICATIONS_TEST: '/v1/admin/notifications/test',
  ADMIN_NOTIFICATIONS_LOG: '/v1/admin/notifications/log',
  MCP_TOKENS: '/v1/mcp/tokens',
  ADMIN_SETTINGS: '/v1/admin/settings',
  ADMIN_SETTINGS_TEST_RPC: '/v1/admin/settings/test-rpc',
  WALLET_NETWORKS: (id: string) => `/v1/wallets/${id}/networks`,
  WALLET_DEFAULT_NETWORK: (id: string) => `/v1/wallets/${id}/default-network`,
  ADMIN_WALLET_BALANCE: (id: string) => `/v1/admin/wallets/${id}/balance`,
  ADMIN_WALLET_TRANSACTIONS: (id: string) => `/v1/admin/wallets/${id}/transactions`,
  ADMIN_API_KEYS: '/v1/admin/api-keys',
  ADMIN_API_KEY: (provider: string) => `/v1/admin/api-keys/${provider}`,
  ADMIN_FOREX_RATES: '/v1/admin/forex/rates',
  ADMIN_TELEGRAM_USERS: '/v1/admin/telegram-users',
  ADMIN_TELEGRAM_USER: (chatId: number) => `/v1/admin/telegram-users/${chatId}`,
} as const;
