// @waiaas/core - shared types, schemas, errors, interfaces

// Enums (12 SSoT enums + EVM/Solana subsets + validateChainNetwork)
export {
  CHAIN_TYPES,
  type ChainType,
  ChainTypeEnum,
  NETWORK_TYPES,
  type NetworkType,
  NetworkTypeEnum,
  EVM_NETWORK_TYPES,
  type EvmNetworkType,
  EvmNetworkTypeEnum,
  SOLANA_NETWORK_TYPES,
  type SolanaNetworkType,
  validateChainNetwork,
  AGENT_STATUSES,
  type AgentStatus,
  AgentStatusEnum,
  TRANSACTION_STATUSES,
  type TransactionStatus,
  TransactionStatusEnum,
  TRANSACTION_TYPES,
  type TransactionType,
  TransactionTypeEnum,
  POLICY_TYPES,
  type PolicyType,
  PolicyTypeEnum,
  POLICY_TIERS,
  type PolicyTier,
  PolicyTierEnum,
  SESSION_STATUSES,
  type SessionStatus,
  SessionStatusEnum,
  NOTIFICATION_EVENT_TYPES,
  type NotificationEventType,
  NotificationEventTypeEnum,
  NOTIFICATION_LOG_STATUSES,
  type NotificationLogStatus,
  NotificationLogStatusEnum,
  AUDIT_ACTIONS,
  type AuditAction,
  AuditActionEnum,
  KILL_SWITCH_STATES,
  type KillSwitchState,
  KillSwitchStateEnum,
  OWNER_STATES,
  type OwnerState,
  OwnerStateEnum,
} from './enums/index.js';

// Schemas (5 domain Zod SSoT schemas + v1.4 discriminatedUnion 5-type)
export {
  AgentSchema,
  type Agent,
  CreateAgentRequestSchema,
  type CreateAgentRequest,
  SessionSchema,
  type Session,
  CreateSessionRequestSchema,
  type CreateSessionRequest,
  TransactionSchema,
  type Transaction,
  SendTransactionRequestSchema,
  type SendTransactionRequest,
  // v1.4 discriminatedUnion 5-type transaction request schemas
  TransactionRequestSchema,
  type TransactionRequest,
  TransferRequestSchema,
  type TransferRequestInput,
  TokenTransferRequestSchema,
  type TokenTransferRequest,
  ContractCallRequestSchema,
  type ContractCallRequest,
  ApproveRequestSchema,
  type ApproveRequest,
  BatchRequestSchema,
  type BatchRequest,
  PolicySchema,
  type Policy,
  CreatePolicyRequestSchema,
  type CreatePolicyRequest,
  UpdatePolicyRequestSchema,
  type UpdatePolicyRequest,
  ConfigSchema,
  type Config,
  AssetInfoSchema,
  type AssetInfoDto,
} from './schemas/index.js';

// Errors (68 error codes + WAIaaSError + ChainError)
export {
  ERROR_CODES,
  type ErrorCode,
  type ErrorDomain,
  type ErrorCodeEntry,
  WAIaaSError,
  ChainError,
  type ChainErrorCategory,
  type ChainErrorCode,
  CHAIN_ERROR_CATEGORIES,
} from './errors/index.js';

// Interfaces (4 contracts + chain adapter types)
export type {
  TokenAmount,
  TransferRequest,
  UnsignedTransaction,
  SimulationResult,
  SubmitResult,
  BalanceInfo,
  HealthInfo,
  AssetInfo,
  // v1.4 new types
  FeeEstimate,
  TokenInfo,
  SweepResult,
  TokenTransferParams,
  ContractCallParams,
  ApproveParams,
  BatchParams,
  IChainAdapter,
  ILocalKeyStore,
  IPolicyEngine,
  PolicyEvaluation,
  INotificationChannel,
  NotificationPayload,
} from './interfaces/index.js';

// i18n (multilingual messages)
export { getMessages, type SupportedLocale, type Messages } from './i18n/index.js';
