name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start the daemon with '...'
        2. Send request to '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: WAIaaS Version
      description: "Output of `waiaas --version`"
      placeholder: "e.g., 2.0.0"
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package is affected?
      options:
        - "@waiaas/daemon"
        - "@waiaas/cli"
        - "@waiaas/sdk"
        - "@waiaas/mcp"
        - "@waiaas/admin"
        - "@waiaas/core"
        - "@waiaas/adapter-solana"
        - "@waiaas/adapter-evm"
        - "waiaas (Python SDK)"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Node.js version, deployment method, etc.
      placeholder: |
        - OS: macOS 15.3
        - Node.js: 22.x
        - Deployment: npm / Docker
        - Chain: Solana Devnet
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any error messages or logs
      render: shell
    validations:
      required: false
