#!/usr/bin/env tsx
/**
 * API Type Generation Pipeline
 *
 * 1. Extracts OpenAPI spec from createApp() via extract-openapi.ts
 * 2. Generates TypeScript types using openapi-typescript
 *
 * Output:
 *   - packages/admin/openapi.json (intermediate, gitignored)
 *   - packages/admin/src/api/types.generated.ts (committed)
 *
 * Usage: pnpm run generate:api-types
 */

import { readFileSync, writeFileSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';
import openapiTS, { astToString } from 'openapi-typescript';

const ROOT = resolve(import.meta.dirname ?? '.', '..');
const OPENAPI_JSON = resolve(ROOT, 'packages', 'admin', 'openapi.json');
const TYPES_OUTPUT = resolve(ROOT, 'packages', 'admin', 'src', 'api', 'types.generated.ts');

const HEADER = `/* eslint-disable */
// This file is auto-generated by scripts/generate-api-types.ts -- DO NOT EDIT
// Source: packages/admin/openapi.json
// Regenerate: pnpm run generate:api-types

`;

async function main(): Promise<void> {
  console.log('=== API Type Generation Pipeline ===\n');

  // Step 1: Extract OpenAPI spec
  console.log('Step 1: Extracting OpenAPI spec...');
  execSync('npx tsx scripts/extract-openapi.ts', {
    cwd: ROOT,
    stdio: 'inherit',
  });

  // Step 2: Generate TypeScript types
  console.log('\nStep 2: Generating TypeScript types from openapi.json...');
  const specContent = readFileSync(OPENAPI_JSON, 'utf-8');
  const spec = JSON.parse(specContent);

  const ast = await openapiTS(spec, {
    exportType: true,
  });
  const source = astToString(ast);

  // Write with header
  const output = HEADER + source;
  writeFileSync(TYPES_OUTPUT, output, 'utf-8');

  // Report results
  const fileSize = statSync(TYPES_OUTPUT).size;
  const lineCount = output.split('\n').length;
  const exportCount = (output.match(/export\s+/g) ?? []).length;

  console.log(`\nType generation complete:`);
  console.log(`  Output: ${TYPES_OUTPUT}`);
  console.log(`  Size: ${(fileSize / 1024).toFixed(1)} KB`);
  console.log(`  Lines: ${lineCount}`);
  console.log(`  Exports: ${exportCount}`);
  console.log(`\nDone.`);
}

main().catch((err) => {
  console.error('Type generation failed:', err);
  process.exit(1);
});
